name: docker build
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2.9
        with:
          dockerfiles: Dockerfile
          image: newtab
          tags: latest

      - name: Push to registry
        uses: redhat-actions/push-to-registry@v2.5
        with:
          image: ${{ steps.build-image.outputs.image }}
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
          tags: latest
